'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import "@fortawesome/fontawesome-svg-core/styles.css"; 
import { config } from "@fortawesome/fontawesome-svg-core";
import Navbar from './_components/Navbar';
import { usePathname } from 'next/navigation';

config.autoAddCss = false; 

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Social Media App',
  description: 'Generated by Ozgun Munar',
}


export default function RootLayout({ children }) {

  const path = usePathname()
  const isPublicPath = path === '/login' || path === '/signup' || path === '/verifyemail'

  return (
    <html lang="en">
      <body className={inter.className}>
        {!isPublicPath && <Navbar />}
        {children}
        </body>
    </html>
  )
}
